web:
    build: images/docker_php_apache
    volumes:
        - ./src:/var/www/html
    ports:
        - "80:80"
    links:
        - db:mysql

db:
    image: mariadb:latest
    hostname: localdb
    environment:
        MYSQL_USER: drupal
        MYSQL_PASSWORD: drupal
        MYSQL_DATABASE: drupal
        MYSQL_ROOT_PASSWORD: 'drupal'
    ports:
        - "3306:3306"
    restart: always
